apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db-deployment.yaml
  - vote-deployment.yaml
  - result-deployment.yaml
  - redis-deployment.yaml
  - worker-deployment.yaml
  - db-service.yaml
  - vote-service.yaml
  - result-service.yaml
  - redis-service.yaml
